### ISSUE TITLE
[Bug]: Deprecation warnings galore upon opening Module Management

### ISSUE THREAD

**Issue by esheyw** [arcanistzed/mcc#27]
### Expected Behavior

I'd really like to not spam my console every time I open MM

### Current Behavior

```
Error: You are accessing BasePackage#data which is now deprecated in favor of referencing schema fields directly on the BasePackage instance.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at get data [as data] (commons.js:11759:7)
    at SpreadsheetController.lookupCompatibility (SpreadsheetController.js:87:14)
    at index.js:51:44
    at NodeList.forEach (<anonymous>)
    at applyModuleManagementColors (index.js:49:82)
```
slightly more than one of these per module, seems like (in my world, 284 warnings for 281 installed modules)

### Steps to Reproduce

1. enable MCC
2. open module management
3. observe console

### Version

1.4.1

### Foundry VTT Version

10.281

### Operating System

Windows 10

### Browser / App

Chrome

### Game System

pf2e 4.7.4

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
You can disable compatibility warnings with `CONFIG.compatibility.mode = CONST.COMPATIBILITY_MODES.SILENT;`
I don't plan on doing this anytime soon, but I'm open to PRs after v11 is stable.
